### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by navdhaagarwal** [timtadh/jpdg#3]
Hi,
I was trying to run the program using the steps given in the readme file. I have installed java 7 along with  Apache Buildr 1.4.15.
But in the step `buildr soot:package` , I get the following error. Can you please help me resolve it.
![image](https://user-images.githubusercontent.com/22665854/66080886-97660480-e584-11e9-8321-0dfe2d76a476.png)
Below is the screenshot after using `buildr soot:package --trace`
![image](https://user-images.githubusercontent.com/22665854/66080996-ced4b100-e584-11e9-9c9f-a108df2d0b97.png)

**Comment by timtadh** [comment]
I really went with the wrong build system when I wrote this. I should have used gradle or maven but at the time it looked like buildr was going to be a thing. Clearly it has a bunch of problems. If I ever get the chance I will redo it.

In the meantime, I did a build that you should hopefully be able to use here: https://github.com/timtadh/jpdg/releases/tag/2017-10-27

Sorry for the problems.
